--- use DB as default one
USE [KRR-PA-CNT-GasForISA95]
GO

-- delete all tables
DROP TABLE [dbo].[CurData]
DROP TABLE [dbo].[SumData]
DROP TABLE [dbo].[PlcCur01]
DROP TABLE [dbo].[PlcCur02]
DROP TABLE [dbo].[PlcCur03]
DROP TABLE [dbo].[PlcCur04]
DROP TABLE [dbo].[PlcCur05]
DROP TABLE [dbo].[PlcCur07]
DROP TABLE [dbo].[PlcCur08]
DROP TABLE [dbo].[PlcCur09]
DROP TABLE [dbo].[PlcCur10]
DROP TABLE [dbo].[PlcCur11]
DROP TABLE [dbo].[PlcSum01]
DROP TABLE [dbo].[PlcSum02]
DROP TABLE [dbo].[PlcSum03]
DROP TABLE [dbo].[PlcSum04]
DROP TABLE [dbo].[PlcSum05]
DROP TABLE [dbo].[PlcSum07]
DROP TABLE [dbo].[PlcSum08]
DROP TABLE [dbo].[PlcSum09]
DROP TABLE [dbo].[PlcSum10]
DROP TABLE [dbo].[PlcSum11]
DROP TABLE [dbo].[TempCur01]
DROP TABLE [dbo].[TempCur02]
DROP TABLE [dbo].[TempCur03]
DROP TABLE [dbo].[TempCur04]
DROP TABLE [dbo].[TempCur05]
DROP TABLE [dbo].[TempCur07]
DROP TABLE [dbo].[TempCur08]
DROP TABLE [dbo].[TempCur09]
DROP TABLE [dbo].[TempCur10]
DROP TABLE [dbo].[TempCur11]
DROP TABLE [dbo].[TempSum01]
DROP TABLE [dbo].[TempSum02]
DROP TABLE [dbo].[TempSum03]
DROP TABLE [dbo].[TempSum04]
DROP TABLE [dbo].[TempSum05]
DROP TABLE [dbo].[TempSum07]
DROP TABLE [dbo].[TempSum08]
DROP TABLE [dbo].[TempSum09]
DROP TABLE [dbo].[TempSum10]
DROP TABLE [dbo].[TempSum11]

GO
